version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=3000
      - REBUILD_PRISMA_CLIENT=true
      - APP_PG_DATABASE_URL=postgresql://postgres:qwerty123@postgres:5432/book_store?schema=public
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=book_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./static:/usr/share/nginx/html:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
